# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

variables:
  host: dev-riskmarketplace.standardbank.co.za

jobs:
- job: jmeter
  pool:
    vmImage: ubuntu-latest
  displayName: Run JMeter tests
  steps:
  - task: Bash@3
    displayName: Execute JMeter tests
    inputs:
      targetType: filePath
      filePath: 'jmeter/test.sh'
      arguments: '$PWD RMP_CreateIncident.jmx $(host)'
      workingDirectory: jmeter
      failOnStderr: true
  - task: PublishPipelineArtifact@1
    displayName: Publish JMeter Report
    inputs:
      targetPath: jmeter/report
      artifact: jmeter